[package]
name = "easy-fs-fuse"
version = "0.1.0"
edition = "2021"


[dependencies]
easyfs = { path = "../easy-fs" }
# clap = { version = "4.2.5", features = ["derive"] }
clap = "2.33.3"
# easyfs = { path = "/home/kyros/WorkStations/TempStorage/rCore-Tutorial-v3/easy-fs" }
rand = "0.8.5"
